### ISSUE TITLE
Missing `src` in Linux `aarch64` & `ppc64le`

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/libcusparse-feedstock#2]
In PR ( https://github.com/conda-forge/libcusparse-feedstock/pull/1 ) while enabling Linux `aarch64` & `ppc64le` builds, noticed that `src` was missing. So the tests (noted below) failed. Have constrained the tests to Linux `x86_64`. Filing this issue for awareness/tracking

https://github.com/conda-forge/libcusparse-feedstock/blob/6a68f87f49e742a295853690027017e161ed1f89/recipe/meta.yaml#L102-L105

**Comment by leofang** [comment]
@adibbley Could this be in the same situation as in `libcublas`? (https://github.com/conda-forge/libcublas-feedstock/pull/6#issuecomment-1498245926)

**Comment by adibbley** [comment]
Yup, confirmed we only ship `src` on `x86_64` here as well. Thanks @leofang and @jakirkham!

**Comment by jakirkham** [comment]
Closing as answered
